sudo: required

language: generic

services:
    - docker

before_install:
    - echo "start creating an image with dockerfile"
    - docker build -t whahn/latest -f Dockerfile.dev .

script:
    - docker run -e CI=true whahn/latest npm run test -- --coverage

after_success:
    - echo "success"
